Unify Bash safety methods

diff --git a/scripts/le-renew-haproxy b/scripts/le-renew-haproxy
--- a/scripts/le-renew-haproxy
+++ b/scripts/le-renew-haproxy
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+set -o errexit      # Exit on most errors (see the manual)
+set -o nounset      # Disallow expansion of unset variables
+set -o pipefail     # Use last non-zero exit code in a pipeline
+set -o errtrace     # Ensure the error trap handler is inherited
+
 export web_service='haproxy'
 export DOMAIN='pct.bike'
 export http_01_port='54321'
diff --git a/scripts/publish-pct-shiny b/scripts/publish-pct-shiny
--- a/scripts/publish-pct-shiny
+++ b/scripts/publish-pct-shiny
@@ -4,7 +4,10 @@
 # Written by Pete Stevens of Mythic Beasts Ltd and Nikolai Berkoff
 # to support NPTC production deployment
 
-set +e
+set -o errexit      # Exit on most errors (see the manual)
+set -o nounset      # Disallow expansion of unset variables
+set -o pipefail     # Use last non-zero exit code in a pipeline
+set -o errtrace     # Ensure the error trap handler is inherited
 
 VAR_DIR="/home/git/var-shiny/"
 WAIT_SECONDS=0
@@ -31,10 +34,10 @@ git --git-dir /home/git/pct-shiny rev-parse --short HEAD > ${VAR_DIR}${SHINY_APP
 echo "Git fetch the data"
 git -C /home/git/${DATA_GIT} fetch
 
-DATASHA=`cat ${VAR_DIR}${SHINY_APP_DIR}/outputs_regional_Rsmall_sha`
+DATASHA=$(cat ${VAR_DIR}${SHINY_APP_DIR}/outputs_regional_Rsmall_sha)
 
 echo "Checkout ${DATASHA} version of the data"
-git -C /home/git/${DATA_GIT} checkout $DATASHA -f
+git -C /home/git/"$DATA_GIT" checkout "$DATASHA" -f
 
 if [[ $(hostname -s) = "npct0" ]]; then
   cp ${VAR_DIR}${SHINY_APP_DIR}/non_www/robots.txt ${VAR_DIR}${SHINY_APP_DIR}/regions_www/robots.txt
diff --git a/scripts/update-server b/scripts/update-server
--- a/scripts/update-server
+++ b/scripts/update-server
@@ -4,6 +4,11 @@
 # Written by Pete Stevens of Mythic Beasts Ltd and Nikolai Berkoff
 # to support NPTC production deployment
 
+set -o errexit      # Exit on most errors (see the manual)
+set -o nounset      # Disallow expansion of unset variables
+set -o pipefail     # Use last non-zero exit code in a pipeline
+set -o errtrace     # Ensure the error trap handler is inherited
+
 export SSH_AUTH_SOCK=''
 echo "Updating $1"
 PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
